---
title: Jasper
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    uploads:
      title: Uploads
      output: true
      email: hi@jusv.co
      description: simple jekyll theme
      baseurl: ''
      url: http://jusv.co
      twitter_username: justina_ugh
      github_username: justinav
      markdown: kramdown
  uploads:
    title: Uploads
    output: true
