---
title: Jasper
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    uploads:
      title: Uploads
      output: true
      email: hi@jusv.co
      description: simple jekyll theme
      twitter_username: justina_ugh
      github_username: justinav
      markdown: kramdown
      permalink: pretty
      github_url: https://github.com/justinav/theme-jasper
      github: [metadata]
      repository: justinav/theme-jasper
      uploads:
        title: Uploads
        output: true
        lsi: false
        safe: true
        source: https://github.com/justinav/theme-jasper
        incremental: false
        highlighter: rouge
        gist:
          noscript: false
          uploads:
            title: Uploads
            output: true
            plugins:
              - "jekyll-github-metadata"
